
import java.sql.Statement;

public class Form_Formulario extends javax.swing.JFrame {

    Statement st;
    private String Codigo;

    public Form_Formulario() {
        initComponents();
        try {
            st = new DBConexao().getConnection();
        } catch (Exception e) {
            System.out.println("Error: " + e.toString() + e.getMessage());
        }
    }

    public Form_Formulario(String codigo) {
        initComponents();
        Codigo = codigo;

        try {
            st = new DBConexao().getConnection();
        } catch (Exception e) {
            System.out.println("Error: " + e.toString() + e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jtfData = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jtfNome = new javax.swing.JTextField();
        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        buttonGroup5 = new javax.swing.ButtonGroup();
        buttonGroup6 = new javax.swing.ButtonGroup();
        jrbQ1O9 = new javax.swing.JRadioButton();
        jrbQ1O10 = new javax.swing.JRadioButton();
        jtfData1 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jtfNome1 = new javax.swing.JTextField();
        jbFinalizar = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jrbQ1O6 = new javax.swing.JRadioButton();
        jrbQ1O7 = new javax.swing.JRadioButton();
        jrbQ1O8 = new javax.swing.JRadioButton();
        jrbQ1O11 = new javax.swing.JRadioButton();
        jrbQ1O12 = new javax.swing.JRadioButton();
        jrbQ1O13 = new javax.swing.JRadioButton();
        jrbQ1O1 = new javax.swing.JRadioButton();
        jrbQ1O14 = new javax.swing.JRadioButton();
        jrbQ1O15 = new javax.swing.JRadioButton();
        jrbQ1O16 = new javax.swing.JRadioButton();
        jrbQ1O2 = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jrbQ1O3 = new javax.swing.JRadioButton();
        jrbQ1O4 = new javax.swing.JRadioButton();
        jrbQ1O5 = new javax.swing.JRadioButton();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        jSeparator7 = new javax.swing.JSeparator();

        jLabel3.setText("Data:");

        jLabel2.setText("Nome:");

        buttonGroup1.add(jrbQ1O9);
        jrbQ1O9.setText("Sim");

        buttonGroup1.add(jrbQ1O10);
        jrbQ1O10.setText("Não");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastrar/Alterar Formulario");

        jLabel4.setText("Data:");

        jLabel5.setText("Nome:");

        jbFinalizar.setText("Finalizar Teste");
        jbFinalizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbFinalizarMouseClicked(evt);
            }
        });

        buttonGroup4.add(jrbQ1O6);
        jrbQ1O6.setText("Não");
        jrbQ1O6.setActionCommand("0");

        buttonGroup3.add(jrbQ1O7);
        jrbQ1O7.setText("Nenhum/Acamado/Repouso leito");
        jrbQ1O7.setActionCommand("0");

        buttonGroup3.add(jrbQ1O8);
        jrbQ1O8.setText("Bengala/Muleta");
        jrbQ1O8.setActionCommand("15");

        buttonGroup6.add(jrbQ1O11);
        jrbQ1O11.setText("Orientado");
        jrbQ1O11.setActionCommand("0");

        buttonGroup6.add(jrbQ1O12);
        jrbQ1O12.setText("Desorientado/Confuso");
        jrbQ1O12.setActionCommand("15");

        buttonGroup5.add(jrbQ1O13);
        jrbQ1O13.setText("Normal/Acamado/Cadeira de rodas");
        jrbQ1O13.setActionCommand("0");

        buttonGroup1.add(jrbQ1O1);
        jrbQ1O1.setText("Sim");
        jrbQ1O1.setActionCommand("25");

        buttonGroup5.add(jrbQ1O14);
        jrbQ1O14.setText("Lenta/Fraca");
        jrbQ1O14.setActionCommand("10");

        buttonGroup5.add(jrbQ1O15);
        jrbQ1O15.setText("Alterada/Cambaleante");
        jrbQ1O15.setActionCommand("20");

        buttonGroup3.add(jrbQ1O16);
        jrbQ1O16.setText("Mobiliário ou parede");
        jrbQ1O16.setActionCommand("30");

        buttonGroup1.add(jrbQ1O2);
        jrbQ1O2.setText("Não");
        jrbQ1O2.setActionCommand("0");

        jLabel1.setText("1- História de quedas nos últimos três meses");

        jLabel6.setText("2- Diagnóstico Secundário");

        jLabel7.setText("3- Auxilio na mobilidade");

        jLabel8.setText("4-Terapia Endovenosa");

        jLabel9.setText("5- Marcha");

        jLabel10.setText("6- Estado Mental");

        buttonGroup2.add(jrbQ1O3);
        jrbQ1O3.setText("Sim");
        jrbQ1O3.setActionCommand("15");

        buttonGroup2.add(jrbQ1O4);
        jrbQ1O4.setText("Não");
        jrbQ1O4.setActionCommand("0");

        buttonGroup4.add(jrbQ1O5);
        jrbQ1O5.setText("Sim");
        jrbQ1O5.setActionCommand("20");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1)
                    .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jSeparator3)
                    .addComponent(jSeparator4, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jSeparator5)
                    .addComponent(jSeparator6)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9)
                            .addComponent(jrbQ1O15)
                            .addComponent(jrbQ1O14)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jrbQ1O5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jrbQ1O6))
                            .addComponent(jrbQ1O13)
                            .addComponent(jLabel10)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jrbQ1O11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jrbQ1O12))
                            .addComponent(jrbQ1O8)
                            .addComponent(jrbQ1O16)
                            .addComponent(jLabel6)
                            .addComponent(jLabel1)
                            .addComponent(jLabel7)
                            .addComponent(jrbQ1O7)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jrbQ1O1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jrbQ1O2))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jrbQ1O3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jrbQ1O4)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jSeparator7, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jrbQ1O1)
                    .addComponent(jrbQ1O2))
                .addGap(1, 1, 1)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jrbQ1O3)
                    .addComponent(jrbQ1O4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jrbQ1O7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jrbQ1O8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jrbQ1O16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jrbQ1O5)
                    .addComponent(jrbQ1O6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jrbQ1O13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jrbQ1O14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jrbQ1O15)
                .addGap(3, 3, 3)
                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jrbQ1O11)
                    .addComponent(jrbQ1O12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel4))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jtfNome1)
                                    .addComponent(jtfData1, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(91, 91, 91))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(84, 84, 84)
                        .addComponent(jbFinalizar)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfNome1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jtfData1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 472, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbFinalizar))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbFinalizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbFinalizarMouseClicked
        System.out.println("Group 1 = " + buttonGroup1.getSelection().getActionCommand());
    }//GEN-LAST:event_jbFinalizarMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Form_Formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Form_Formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Form_Formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Form_Formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Form_Formulario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.ButtonGroup buttonGroup5;
    private javax.swing.ButtonGroup buttonGroup6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JButton jbFinalizar;
    private javax.swing.JRadioButton jrbQ1O1;
    private javax.swing.JRadioButton jrbQ1O10;
    private javax.swing.JRadioButton jrbQ1O11;
    private javax.swing.JRadioButton jrbQ1O12;
    private javax.swing.JRadioButton jrbQ1O13;
    private javax.swing.JRadioButton jrbQ1O14;
    private javax.swing.JRadioButton jrbQ1O15;
    private javax.swing.JRadioButton jrbQ1O16;
    private javax.swing.JRadioButton jrbQ1O2;
    private javax.swing.JRadioButton jrbQ1O3;
    private javax.swing.JRadioButton jrbQ1O4;
    private javax.swing.JRadioButton jrbQ1O5;
    private javax.swing.JRadioButton jrbQ1O6;
    private javax.swing.JRadioButton jrbQ1O7;
    private javax.swing.JRadioButton jrbQ1O8;
    private javax.swing.JRadioButton jrbQ1O9;
    private javax.swing.JTextField jtfData;
    private javax.swing.JTextField jtfData1;
    private javax.swing.JTextField jtfNome;
    private javax.swing.JTextField jtfNome1;
    // End of variables declaration//GEN-END:variables
}
