import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class Form_Paciente extends javax.swing.JFrame {

    Statement st;
    DefaultTableModel modelo;
    private int CodigoEditar = 0;
    private String Nome;
    private Date DataNasc;

    public Form_Paciente() {
        //construtor do incluir
        initComponents();
        this.setLocationRelativeTo(null);
        try {
            st = new DBConexao().getConnection();
        } catch (Exception e) {
            System.out.println("Error: " + e.toString() + e.getMessage());
        }
    }

    public Form_Paciente(int codigo) {
        //construtor do editar
        initComponents();
        this.setLocationRelativeTo(null);
        CodigoEditar = codigo;
        try {
            st = new DBConexao().getConnection();
        } catch (Exception e) {
            System.out.println("Error: " + e.toString() + e.getMessage());
        }
        BuscaValorEditar();
    }

    public void BuscaValorEditar() {
        try {
            String sql = "SELECT codigo, nome, DATE_FORMAT(data_nascimento, '%d/%m/%Y') as data_nascimento FROM Paciente WHERE codigo=" + CodigoEditar;
            System.out.println(sql);
            ResultSet rec = st.executeQuery(sql);
            while (rec.next()) {
                jtfNome.setText(rec.getString("nome"));
                jtfDataNasc.setText(rec.getString("data_nascimento"));
            }
        } catch (SQLException s) {
            JOptionPane.showMessageDialog(this, "Erro ao listar!! " + s.toString());
        }
    }

    private void BuscaValorCampos() {
        Nome = jtfNome.getText();
        DataNasc = Utilidades.StringToDate(jtfDataNasc.getText());
        DataNasc = new java.sql.Date(DataNasc.getTime());
    }

    public void Alterar() {
        BuscaValorCampos();

        String set = " SET nome='" + Nome + "', data_nascimento='" + DataNasc + "'";
        String where = " WHERE codigo=" + CodigoEditar;
        String sql = "UPDATE Paciente" + set + where;

        try {
            int resp = st.executeUpdate(sql);
            if (resp == 1) {
                List_Paciente frame = new List_Paciente();
                frame.setVisible(true);
                this.dispose();
            }
        } catch (SQLException s) {
            JOptionPane.showMessageDialog(this, "Informações não alteradas!! " + s.toString());
        }
    }

    public void Incluir() {
        BuscaValorCampos();

        String values = "'" + Nome + "', '" + DataNasc + "'";
        String sql = "INSERT INTO Paciente (nome, data_nascimento) VALUES(" + values + ")";

        System.out.println(sql);
        try {
            int resp = st.executeUpdate(sql);
            System.out.println("ue");
            if (resp == 1) {
                List_Paciente frame = new List_Paciente();
                frame.setVisible(true);
                this.dispose();
            }
        } catch (SQLException s) {
            JOptionPane.showMessageDialog(this, "Informações não incluida!! " + s.toString());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jbSalvar = new javax.swing.JButton();
        jtfDataNasc = new javax.swing.JTextField();
        jtfNome = new javax.swing.JTextField();
        jbMenu = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Form Paciente");

        jLabel4.setText("Nome:");

        jLabel5.setText("Data Nasc.:");

        jbSalvar.setText("Salvar");
        jbSalvar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbSalvarMouseClicked(evt);
            }
        });

        jbMenu.setText("<<< Voltar");
        jbMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbMenuMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jtfNome)
                            .addComponent(jtfDataNasc, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jbMenu)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jbSalvar)))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jtfDataNasc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbSalvar)
                    .addComponent(jbMenu))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbSalvarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbSalvarMouseClicked
        String dataRecebida = jtfDataNasc.getText();
        if (Utilidades.DataValida(dataRecebida)) {
            if (CodigoEditar > 0) {
                Alterar();
            } else {
                Incluir();
            }
        } else {
            JOptionPane.showMessageDialog(this, "Data no Formato Inválido!!\nA data deve estar no formato dd/MM/yyyy");
        }
    }//GEN-LAST:event_jbSalvarMouseClicked

    private void jbMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbMenuMouseClicked
        List_Paciente form = new List_Paciente();
        form.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jbMenuMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Form_Paciente.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Form_Paciente.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Form_Paciente.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Form_Paciente.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Form_Paciente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JButton jbMenu;
    private javax.swing.JButton jbSalvar;
    private javax.swing.JTextField jtfDataNasc;
    private javax.swing.JTextField jtfNome;
    // End of variables declaration//GEN-END:variables
}
